config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Local tp App
    path("", include("tp.urls")),
]

tp/urls.py
#tp/urls.py
from django.urls import path
from django.urls import re_path as url

from wkhtmltopdf.views import PDFTemplateView

from . import views
from . import pdfviews
from .views import SignupPageView


urlpatterns = [
	#path("", HomePageView.as_view(), name="home"),
	path("signup/", SignupPageView.as_view(), name="signup"),

	path('', views.add_student, name="home"),
	path('add_student/', views.add_student, name="add_student"),
    path('add_student_save/', views.add_student_save, name="add_student_save"),
    path('check_matricule_exist/', views.check_matricule_exist, name="check_matricule_exist"),
    path('validate_telephone/', views.validate_telephone, name="validate_telephone"),

	path('edit_student/<student_id>', views.edit_student, name="edit_student"),
    path('edit_student_save/', views.edit_student_save, name="edit_student_save"),
    path('manage_student/', views.manage_student, name="manage_student"),
    path('delete_student/<student_id>/', views.delete_student, name="delete_student"),

    path('add_department/', views.add_department, name="add_department"),
    path('add_department_save/', views.add_department_save, name="add_department_save"),
    path('manage_department/', views.manage_department, name="manage_department"),
    path('edit_department/<department_id>/', views.edit_department, name="edit_department"),
    path('edit_department_save/', views.edit_department_save, name="edit_department_save"),
    path('delete_department/<department_id>/', views.delete_department, name="delete_department"),

    path('add_option/', views.add_option, name="add_option"),
    path('add_option_save/', views.add_option_save, name="add_option_save"),
    path('manage_option/', views.manage_option, name="manage_option"),
    path('edit_option/<option_id>/', views.edit_option, name="edit_option"),
    path('edit_option_save/', views.edit_option_save, name="edit_option_save"),
    path('delete_option/<option_id>/', views.delete_option, name="delete_option"),
    
    path('manage_session/', views.manage_session, name="manage_session"),
    path('add_session/', views.add_session, name="add_session"),
    path('add_session_save/', views.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', views.edit_session, name="edit_session"),
    path('edit_session_save/', views.edit_session_save, name="edit_session_save"),
    path('delete_session/<session_id>/', views.delete_session, name="delete_session"),

    path('add_town/', views.add_town, name="add_town"),
    path('add_town_save/', views.add_town_save, name="add_town_save"),
    path('manage_town/', views.manage_town, name="manage_town"),
    path('edit_town/<town_id>/', views.edit_town, name="edit_town"),
    path('edit_town_save/', views.edit_town_save, name="edit_town_save"),
    path('delete_town/<town_id>/', views.delete_town, name="delete_town"),

    path('manage_school/', views.manage_school, name="manage_school"),
    path('add_school/', views.add_school, name="add_school"),
    path('add_school_save/', views.add_school_save, name="add_school_save"),
    path('edit_school/<school_id>', views.edit_school, name="edit_school"),
    path('edit_school_save/', views.edit_school_save, name="edit_school_save"),
    path('delete_school/<school_id>/', views.delete_school, name="delete_school"),

    path('add_school_dept/', views.add_school_dept, name="add_school_dept"),
    path('add_school_dept_save/', views.add_school_dept_save, name="add_school_dept_save"),
    path('manage_school_dept/', views.manage_school_dept, name="manage_school_dept"),
    path('edit_school_dept/<school_dept_id>/', views.edit_school_dept, name="edit_school_dept"),
    path('edit_school_dept_save/', views.edit_school_dept_save, name="edit_school_dept_save"),
    path('delete_school_dept/<school_dept_id>/', views.delete_school_dept, name="delete_school_dept"),
    
    path('admin_home/', views.admin_home, name="admin_home"),
    path('admin_profile/', views.admin_profile, name="admin_profile"),
    path('admin_profile_update/', views.admin_profile_update, name="admin_profile_update"),

    path('student_pdf_generate/(?P<student_id>.*)/$', pdfviews.student_pdf_generate, name="student_pdf_generate"),
    path('student/', pdfviews.student, name="student")

]

tp/forms.py
from django import forms 
from django.forms import Form
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import academicSession, Level, Department, Option, School, SchoolDept


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class tpRegisterForm(forms.Form):

    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Name","class":"form-control"}))
    matricule = forms.CharField(max_length=8, widget=forms.TextInput(attrs={"placeholder": "Enter your Matricule No.","class":"form-control"}))
    telephone = forms.CharField(max_length=9, widget=forms.TextInput(attrs={"placeholder": "Enter your Phone No.","class":"form-control"}))

    session_year_list = []
    department_list = []
    option_list = []
    level_list = []
    school_list = []
    school_dept_list = []

    # Displaying Academic Session years
    try:
        session_years = academicSession.objects.all()
        for session_year in session_years:
            start_year = session_year.session_start_year.strftime('%Y')
            end_year = session_year.session_end_year.strftime('%Y')
            single_session_year = (session_year.id, str(start_year)+" / "+str(end_year))
            session_year_list.append(single_session_year)
    except:
        session_year_list = []


    # Displaying the various departments
    try:
        departments = Department.objects.all()
        for department in departments:
            single_department = (department.id, department.name)
            department_list.append(single_department)
    except:
        department_list = [] 


    # Display various options
    try:
        options = Option.objects.all()
        for option in options:
            single_option = (option.id, option.name)
            option_list.append(single_option)
    except:
        option_list = []


    # Display various levels
    try:
        levels = Level.objects.all()
        for level in levels:
            single_level = (level.id, level.name)
            level_list.append(single_level)
    except:
        level_list = []


    # Display various tp schools
    try:
        schools = School.objects.all()
        for school in schools:
            single_school = (school.id, school.name)
            school_list.append(single_school)
    except:
        school_list = []


    # Display carious tp school departments
    try:
        schoolDepts = SchoolDept.objects.all()
        for schoolDept in schoolDepts:
            single_school_dept = (schoolDept.id, schoolDept.name)
            school_dept_list.append(single_school_dept)
    except:
        school_dept_list = []

        
    
    department = forms.ChoiceField(label="Department", choices=department_list, widget=forms.Select(attrs={"class":"form-control"}))
    option = forms.ChoiceField(label="Option", choices=option_list, widget=forms.Select(attrs={"class":"form-control"}))
    level = forms.ChoiceField(label="Level", choices=level_list, widget=forms.Select(attrs={"class":"form-control"}))
    school = forms.ChoiceField(label="TP School", choices=school_list, widget=forms.Select(attrs={"class":"form-control"}))
    school_dept = forms.ChoiceField(label="School Department", choices=school_dept_list, widget=forms.Select(attrs={"class":"form-control"}))

    academic_session = forms.ChoiceField(label="Academic Session", choices=session_year_list, disabled = True)




class tpUpdateForm(forms.Form):

    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    matricule = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Matricule No'}))
    telephone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Telephone No'}))

    session_year_list = []
    department_list = []
    option_list = []
    level_list = []
    school_list = []
    school_dept_list = []

    # Displaying Academic Session years
    try:
        session_years = academicSession.objects.all()
        for session_year in session_years:
            start_year = session_year.session_start_year.strftime('%Y')
            end_year = session_year.session_end_year.strftime('%Y')
            single_session_year = (session_year.id, str(start_year)+" / "+str(end_year))
            session_year_list.append(single_session_year)
    except:
        session_year_list = []


    # Displaying the various departments
    try:
        departments = Department.objects.all()
        for department in departments:
            single_department = (department.id, department.name)
            department_list.append(single_department)
    except:
        department_list = [] 


    # Display various options
    try:
        options = Option.objects.all()
        for option in options:
            single_option = (option.id, option.name)
            option_list.append(single_option)
    except:
        option_list = []


    # Display various levels
    try:
        levels = Level.objects.all()
        for level in levels:
            single_level = (level.id, level.name)
            level_list.append(single_level)
    except:
        level_list = []


    # Display various tp schools
    try:
        schools = School.objects.all()
        for school in schools:
            single_school = (school.id, school.name)
            school_list.append(single_school)
    except:
        school_list = []


    # Display carious tp school departments
    try:
        schoolDepts = SchoolDept.objects.all()
        for schoolDept in schoolDepts:
            single_school_dept = (schoolDept.id, schoolDept.name)
            school_dept_list.append(single_school_dept)
    except:
        school_dept_list = []

        
    
    department = forms.ChoiceField(label="Department", choices=department_list, widget=forms.Select(attrs={"class":"form-control"}))
    option = forms.ChoiceField(label="Option", choices=option_list, widget=forms.Select(attrs={"class":"form-control"}))
    level = forms.ChoiceField(label="Level", choices=level_list, widget=forms.Select(attrs={"class":"form-control"}))
    school = forms.ChoiceField(label="TP School", choices=school_list, widget=forms.Select(attrs={"class":"form-control"}))
    school_dept = forms.ChoiceField(label="School Department", choices=school_dept_list, widget=forms.Select(attrs={"class":"form-control"}))

    academic_session = forms.ChoiceField(label="Academic Session", choices=session_year_list)

templates/_base.html
<!-- templates/_base.html -->
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}HTTTC KBA{% endblock title %}</title>
{% load static %}
<link href="https://fonts.googleapis.com/css?family=\
Source+Sans+Pro:400" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/base.css' %}">

<!-- Boostrap CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

{% block content %}

{% endblock content %}

<!-- JavaScript -->


<script src="{% static "jquery/jquery.min.js"  %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "jquery-ui/jquery-ui.min.js"  %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>

{% comment %} For Custom CSS {% endcomment %}
{% block custom_js %}
{% endblock custom_js %}

</div>
</body>
</html>

templates/home.html
{% extends '_base.html' %}

{% block page_title %}
    TP Registration | HTTTC Kumba
{% endblock page_title %}

{% block content %}

{% load static %}

<style type="text/css">
    .content{
      margin: auto;
      width: 80%;
    }
    .form-group{
      padding: 10px  0px 10px;
    }
    label{
      font-weight: bold;
    }
    .header_below{
      padding-top: 14px;
      margin-top: 35px;
      margin-bottom: 20px;
    }
    .alert-danger {
      color: #fff;
      background: #dc3545;
      border-color: #d32535;
    }
    .alert-dismissible .close {
      position: absolute;
      top: 0;
      right: 0;
      padding: 0.75rem 1.25rem;
      }
    button.close, button.mailbox-attachment-close {
      background-color: transparent;
    }
    .alert .close{
      color: #000;
      opacity: 1;
      border: none;
}
  </style>

<section class="content">

        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                      <div class="row">
                        <div class="col-md-4">

                          <div class="image">
                            <img src="{% static 'dist/img/httclogo.png' %}" class="img-circle elevation-2" alt="HTTTC">
                          </div>
                        </div>
                        <div class="col-md-4 offset-md-4">.
                          <h3 class="card-title">Teaching Practice Registration</h3>
                        </div>
                      </div>
                    </div>
                    
                    <!-- /.card-header -->
                    <!-- form start -->
                    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h5 class="card-title"><i style="padding-left: 20px;">Please FILL out the form bellow to complete your Teaching Practice Registration</i></h5>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_student_save' %}">
                        {% csrf_token %}

                        
                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            

                        <div class="card-body">

                            <div class="card-header header_below">
                              <h5 class="card-title" aria-describedby="sinfotHelp"><i>Personal Information</i></h5>
                              <small id="sinfotHelp" class="form-text text-muted">Enter your student information .</small>
                            </div>

                            <div class="form-group">
                                <label> Name </label>
                                <input type="text" class="form-control" name="name" placeholder="Enter Name">
                            </div>

                            <div class="form-group">
                                <label>Matricule </label>
                                <input type="text" maxlength="8" class="form-control" name="matricule" id="id_matricule" placeholder="Enter Matricule" style="text-transform: uppercase;">
                            </div>

                            <div class="form-group">
                                <label>Telephone </label>
                                <input type="text" maxlength="9" class="form-control" name="telephone" id="id_telephone" placeholder="Enter Phone No.">
                            </div>

                            <div class="form-group">
                                <label>Level </label>
                                <select class="form-control" name="level">
                                    {% for level in levels %}
                                        <option value="{{ level.id }}">{{ level.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Department </label>
                                <select class="form-control" name="department" id="select1">
                                    {% for department in departments %}
                                        <option value="{{ department.id }}">{{ department.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Option </label>
                                <select class="form-control" name="option" id="select2">
                                    {% for option in options %}
                                        <option value="{{ option.id }}" labels="{{ option.department_id }}">{{ option.name }} </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="card-header header_below">
                              <h5 class="card-title" aria-describedby="pinfotHelp"><i>School Information</i></h5>
                              <small id="pinfotHelp" class="form-text text-muted">Information about the school you would like to teach in.</small>
                            </div>

                          <div class="form-group">
                                <label>TP School </label>
                                <select class="form-control" name="school" id="select_school">
                                    <option selected disabled=True>--Choose  School</option>
                                    {% for school in schools %}
                                        <option value="{{ school.id }}"{% if school.num_of_sudent == 1 %} disabled {% endif %}>{{ school.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label>TP School Department </label>
                                <select class="form-control" name="school_dept" id="select_school_dept">
                                    <option selected disabled=True>--Choose Department</option>
                                    {% for school_dept in school_depts %}
                                        <option value="{{ school_dept.id }}" labels="{{ school_dept.school_id }}">{{ school_dept.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group" style="visibility: hidden;">
                                <label>Academic Session </label>
                                <select name="academic_session">
                                    {% for academic_session in academic_sessions %}
                                        <option value="{{ academic_session.id }}">{{ academic_year}}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
</section>

                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock content %}

  {% block custom_js %}
    {% comment %} Checking if matricule already exists or not usin Ajax {% endcomment %}

  <script>
        
        $(document).ready(function(){
            // Dependent List
            // Dependent selection for School and School Department
            var $select1=$('#select1'),
                $select2=$('#select2'),
                $select_school=$('#select_school'),
                $select_school_dept=$('#select_school_dept'),

                $options=$select_school_dept.find('option');
                $option_options=$select2.find('option');

                $select_school.on('change', function(){
                    $select_school_dept.html($options.filter('[labels="'+this.value+'"]'));
                }).trigger('change');

                $select1.on('change', function(){
                    $select2.html($option_options.filter('[labels="'+this.value+'"]'));
                }).trigger('change');

            // Checking if matricule already exists
            // keyup event will be triggered when user leaves keyboard
            $("#id_matricule").keyup(function(){
                var matricule = $(this).val();

                if(matricule!=""){
                    $.ajax({
                        url : '{% url 'check_matricule_exist' %}',
                        type : 'POST',
                        data : {matricule:matricule}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".matricule_error").remove();
                            $("<span class='matricule_error' style='color: red; padding: 5px; font-style: italic;'> Matricule Number Already Registered. </span>").insertAfter("#id_matricule")
                        }
                        else{
                            $(".matricule_error").remove();
                            $("<span class='matricule_error' style='color: green; padding: 5px; font-style: italic;'> Mat Available. </span>").insertAfter("#id_matricule")
                        }
                        
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".matricule_error").remove();
                }
                
            })

            /////////////////////
            $("#id_telephone").keyup(function(){
                var telephone = $(this).val();

                if(telephone!=""){
                    $.ajax({
                        url : '{% url 'validate_telephone' %}',
                        type : 'POST',
                        data : {telephone:telephone}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".phone_error").remove();
                            $("<span class='phone_error' style='color: green; padding: 5px; font-style: italic;'> Valid. </span>").insertAfter("#id_telephone")
                            
                        }
                        else{
                            $(".phone_error").remove();
                            $("<span class='phone_error' style='color: red; padding: 5px; font-style: italic;'> Invalid Phone Number. </span>").insertAfter("#id_telephone")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".phone_error").remove();
                }
                
            })

        })
    </script>

  {% endblock custom_js %}